"""Keyword suggestions generated by an LLM, embedded for similarity search.

The pipeline:
  1. Scheduler asks the active LLM provider for trend candidates (BR).
  2. Each candidate is embedded via sentence-transformers (384-d).
  3. We store the row with status='pending'.
  4. Recurrence test: if at least 2 prior suggestions exist with cosine
     similarity >= 0.85, mark status='auto_promoted' and create a
     KeywordIdea linked via promoted_keyword_id.
  5. UI shows 'pending' rows in a manual inbox; 'auto_promoted' rows are
     visible for transparency but already in the radar.
"""
from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from uuid import UUID, uuid4

from pgvector.sqlalchemy import Vector
from sqlalchemy import DateTime, ForeignKey, Numeric, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from backend.infra.db.base import Base


# Embedding dimension for intfloat/multilingual-e5-small.
EMBEDDING_DIM = 384


class LLMSuggestion(Base):
    __tablename__ = "llm_suggestions"

    id: Mapped[UUID] = mapped_column(PG_UUID(as_uuid=True), primary_key=True, default=uuid4)
    term: Mapped[str] = mapped_column(String(160), nullable=False)
    rationale: Mapped[str | None] = mapped_column(Text)
    temporal_window: Mapped[str] = mapped_column(
        String(10), nullable=False, default="week"
    )  # LLM's stated reason
    provider: Mapped[str] = mapped_column(String(20), nullable=False)  # anthropic | gemini
    embedding: Mapped[list[float] | None] = mapped_column(Vector(EMBEDDING_DIM))
    raw_response: Mapped[dict | None] = mapped_column(JSONB)
    recurrence_score: Mapped[Decimal] = mapped_column(
        Numeric(6, 4), nullable=False, default=Decimal("0")
    )  # max cosine similarity vs prior suggestions (0..1)
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="pending"
    )  # pending | auto_promoted | promoted | dismissed | expired
    promoted_keyword_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True), ForeignKey("keyword_ideas.id", ondelete="SET NULL")
    )
    suggested_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
