"""baseline

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-06-07 12:24:56.154790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('material_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('density_g_cm3', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('price_per_kg_ref', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('failure_rate_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_material_current', 'material_versions', ['material_code', 'is_current'], unique=False)
    op.create_index(op.f('ix_material_versions_material_code'), 'material_versions', ['material_code'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('default_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('energy_kwh_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('printer_power_w', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('printer_depreciation_per_hour', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('business_name', sa.String(length=120), nullable=False),
    sa.Column('business_tagline', sa.String(length=200), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('brand_color_primary', sa.String(length=9), nullable=False),
    sa.Column('stalled_quote_alert_days', sa.Integer(), nullable=False),
    sa.Column('low_spool_threshold_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_code', sa.String(length=40), nullable=False),
    sa.Column('supplier', sa.String(length=120), nullable=True),
    sa.Column('batch_code', sa.String(length=120), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purchased_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('initial_grams', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_grams', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spools_material_code'), 'spools', ['material_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('quotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('markup_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('min_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('produced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('gcode_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('material_version_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('depreciation_rate_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('failure_rate_override', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['material_version_id'], ['material_versions.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watcher_inbox_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=False),
    sa.Column('original_path', sa.String(length=500), nullable=False),
    sa.Column('parsed_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watcher_inbox_files_file_hash'), 'watcher_inbox_files', ['file_hash'], unique=True)
    op.create_table('material_consumptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quote_item_id', sa.UUID(), nullable=False),
    sa.Column('spool_id', sa.UUID(), nullable=False),
    sa.Column('grams_used', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unit_cost_snapshot', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['quote_item_id'], ['quote_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spool_id'], ['spools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_consumptions')
    op.drop_index(op.f('ix_watcher_inbox_files_file_hash'), table_name='watcher_inbox_files')
    op.drop_table('watcher_inbox_files')
    op.drop_table('quote_services')
    op.drop_table('quote_items')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_spools_material_code'), table_name='spools')
    op.drop_table('spools')
    op.drop_table('settings')
    op.drop_table('services')
    op.drop_index(op.f('ix_material_versions_material_code'), table_name='material_versions')
    op.drop_index('ix_material_current', table_name='material_versions')
    op.drop_table('material_versions')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
