"""quote_items_material_nullable

Revision ID: 0002_qi_material_nullable
Revises: 0001_baseline
Create Date: 2026-06-07 18:27:39.670807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_qi_material_nullable'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quote_items', 'material_version_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quote_items', 'material_version_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
